/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Circus
 */
public class FrmNuevaSolicitud extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmNuevaSolicitud
     */
    public FrmNuevaSolicitud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnnuevaSolicitud = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblSolicitud = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        cbmproveedores = new javax.swing.JComboBox<>();
        cbmEmpleado = new javax.swing.JComboBox<>();
        cbmsolicitud = new javax.swing.JComboBox<>();
        lbldetalleVihiculo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdetalle = new javax.swing.JTextArea();

        setTitle("Nueva Solicitud");

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        btnnuevaSolicitud.setBackground(new java.awt.Color(36, 47, 65));
        btnnuevaSolicitud.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        btnnuevaSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevaSolicitud.setText("Nueva Solicitud");
        btnnuevaSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnuevaSolicitudMouseClicked(evt);
            }
        });
        btnnuevaSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevaSolicitudActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(36, 47, 65));
        btnSalir.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(36, 47, 65));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Solicitud", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        lblSolicitud.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        lblSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        lblSolicitud.setText("Solicitud");

        lblEmpleado.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpleado.setText("Empleado");

        lblFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha");

        lblProveedor.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblProveedor.setText("Proveedor");

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        cbmproveedores.setBackground(new java.awt.Color(36, 47, 65));
        cbmproveedores.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        cbmproveedores.setForeground(new java.awt.Color(255, 255, 255));
        cbmproveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proveedor1", "Proveedor2", "Proveedor3", "Proveedor4", "Proveedor5" }));
        cbmproveedores.setBorder(null);

        cbmEmpleado.setBackground(new java.awt.Color(36, 47, 65));
        cbmEmpleado.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        cbmEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        cbmEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado1", "Empleado2", "Empleado3", "Empleado4", "Empleado5" }));
        cbmEmpleado.setBorder(null);

        cbmsolicitud.setBackground(new java.awt.Color(36, 47, 65));
        cbmsolicitud.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        cbmsolicitud.setForeground(new java.awt.Color(255, 255, 255));
        cbmsolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solicitud 1", "Solicitud 2", "Solicitud 3", "Solicitud 4" }));
        cbmsolicitud.setBorder(null);

        lbldetalleVihiculo.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        lbldetalleVihiculo.setForeground(new java.awt.Color(255, 255, 255));
        lbldetalleVihiculo.setText("Detalle de vehiculo");

        txtdetalle.setBackground(new java.awt.Color(36, 47, 65));
        txtdetalle.setColumns(20);
        txtdetalle.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        txtdetalle.setForeground(new java.awt.Color(255, 255, 255));
        txtdetalle.setRows(5);
        txtdetalle.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtdetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdetalleKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtdetalle);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSolicitud)
                    .addComponent(lblEmpleado)
                    .addComponent(lblFecha)
                    .addComponent(lblProveedor)
                    .addComponent(lbldetalleVihiculo))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbmsolicitud, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbmEmpleado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cbmproveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSolicitud)
                    .addComponent(cbmsolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpleado)
                    .addComponent(cbmEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProveedor)
                    .addComponent(cbmproveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lbldetalleVihiculo)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnnuevaSolicitud)
                .addGap(87, 87, 87)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnuevaSolicitud)
                    .addComponent(btnSalir))
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevaSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnuevaSolicitudMouseClicked
        if (this.txtdetalle.getText().isEmpty()  ){
            JOptionPane.showMessageDialog(this, "Campos vacios","Error", JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_btnnuevaSolicitudMouseClicked

    private void btnnuevaSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevaSolicitudActionPerformed

    }//GEN-LAST:event_btnnuevaSolicitudActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtdetalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdetalleKeyTyped
        char validar = evt.getKeyChar();
        if(!Character.isLetter(validar) && validar != KeyEvent.VK_SPACE ){
            evt.consume();
        }  if( this.txtdetalle.getText().length() == 100 ){
            evt.consume();
        }
    }//GEN-LAST:event_txtdetalleKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnnuevaSolicitud;
    private javax.swing.JComboBox<String> cbmEmpleado;
    private javax.swing.JComboBox<String> cbmproveedores;
    private javax.swing.JComboBox<String> cbmsolicitud;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblSolicitud;
    private javax.swing.JLabel lbldetalleVihiculo;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextArea txtdetalle;
    // End of variables declaration//GEN-END:variables
}
