/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author joe
 */
public class Prueba extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuBuscarVehiculo = new javax.swing.JMenuItem();
        menuAgregarVehiculo = new javax.swing.JMenuItem();
        menuAnularVehiculo = new javax.swing.JMenuItem();
        menuEditarVehiculo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktop.setBackground(new java.awt.Color(36, 47, 65));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );

        jMenu1.setText("Vehiculos");

        menuBuscarVehiculo.setText("Buscar Vehiculo");
        menuBuscarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuBuscarVehiculoMousePressed(evt);
            }
        });
        jMenu1.add(menuBuscarVehiculo);

        menuAgregarVehiculo.setText("Agregar Vehiculo");
        menuAgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarVehiculoActionPerformed(evt);
            }
        });
        jMenu1.add(menuAgregarVehiculo);

        menuAnularVehiculo.setText("Anular Vehiculo");
        menuAnularVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuAnularVehiculoMousePressed(evt);
            }
        });
        jMenu1.add(menuAnularVehiculo);

        menuEditarVehiculo.setText("Editar Vehiculo");
        menuEditarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuEditarVehiculoMousePressed(evt);
            }
        });
        jMenu1.add(menuEditarVehiculo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarVehiculoActionPerformed
        // TODO add your handling code here:
        FrmagregarVehiculo agregar = new FrmagregarVehiculo();
        desktop.add(agregar);
        agregar.setVisible(true);
    }//GEN-LAST:event_menuAgregarVehiculoActionPerformed

    private void menuBuscarVehiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBuscarVehiculoMousePressed
        // TODO add your handling code here:
        FrmbuscarVehiculos buscar = new FrmbuscarVehiculos();
        desktop.add(buscar);
        buscar.setVisible(true);
    }//GEN-LAST:event_menuBuscarVehiculoMousePressed

    private void menuAnularVehiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAnularVehiculoMousePressed
        // TODO add your handling code here:
        FrmanularVehiculos anular = new FrmanularVehiculos();
        desktop.add(anular);
        anular.setVisible(true);
    }//GEN-LAST:event_menuAnularVehiculoMousePressed

    private void menuEditarVehiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEditarVehiculoMousePressed
        // TODO add your handling code here:
        FrmEditarVehiculos editar = new FrmEditarVehiculos();
        desktop.add(editar);
        editar.setVisible(true);
    }//GEN-LAST:event_menuEditarVehiculoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba().setVisible(true);
            }
        });
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAgregarVehiculo;
    private javax.swing.JMenuItem menuAnularVehiculo;
    private javax.swing.JMenuItem menuBuscarVehiculo;
    private javax.swing.JMenuItem menuEditarVehiculo;
    // End of variables declaration//GEN-END:variables
}
